const data = {
  products: [
    {
      _id: "1",
      name: "Veg Tiffin lunch",
      category: "lunch",
      image: "p1.jpg",
      price: 150,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Non Veg Tiffin lunch",
      category: "lunch",
      image: "p2.jpg",
      price: 100,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Veg and Non-Veg mix lunch",
      category: "lunch",
      image: "p3.jpg",
      price: 170,
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Veg Breakfast",
      category: "breakfast",
      image: "p4.jpg",
      price: 170,
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Non Veg Breakfast",
      category: "breakfast",
      image: "p5.jpg",
      price: 120,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Catering menu",
      category: "catering",
      image: "p6.jpg",
      price: 110,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
